/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api.dto;

public class DeniedRequestDTO {
	public final String message;

	public DeniedRequestDTO (String message) {
		this.message = message;
	}
}