/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api.dto;

public class EndTurnRequestDTO {
	public String[] selectedCards;
	
	public EndTurnRequestDTO (String[] selectedCards) {
		this.selectedCards = selectedCards;
	}
	
	public EndTurnRequestDTO () {};
}