/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api.dto;
import eldorado.domain.*;

public class FieldDTO {
	public CoordinatesDTO coordinatesDTO;
	public Field fieldStateDTO;
	
	public FieldDTO (String xyzStringKey, Field field) {
		this.coordinatesDTO = new CoordinatesDTO(xyzStringKey);
		this.fieldStateDTO = field;
	}
}