/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api.dto;

import eldorado.domain.*;

public class GameStateDTO {
	public final MapStateDTO mapStateDTO;
	public final int winningPawnId;
	
	public GameStateDTO (Game game) {
		this.mapStateDTO = new MapStateDTO(game.getMap());
		this.winningPawnId = game.getWinningPawnId();
	}
}