/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api.dto;

import java.util.Map;
import eldorado.domain.*;

public class MapStateDTO {
	public final FieldDTO[] fieldDTOs;
	public final String separator = MapConfiguration.separator;
	public final String[] fieldTypes = MapConfiguration.fieldTypes;
	
	public MapStateDTO (MapConfiguration map) {
		this.fieldDTOs = convertMapToJSONableArrayDTO(map.fields);
	}
		
	private FieldDTO[] convertMapToJSONableArrayDTO (Map<String, Field> fieldsMap) {
		FieldDTO[] fieldsArray = new FieldDTO[fieldsMap.size()];
		int i = 0;
		for (Map.Entry<String, Field> fieldEntry: fieldsMap.entrySet()) {
			fieldsArray[i] = new FieldDTO(fieldEntry.getValue(), fieldEntry.getKey());
			i++;
		}
		return fieldsArray;
	}
}