/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api.dto;

public class MovePawnRequestDTO {
	public int pawnId;
	public int x;
	public int y;
	public int z;
	
	public MovePawnRequestDTO (int pawnId, int x, int y, int z) {
		this.pawnId = pawnId;
		this.x = x;
		this.y = y;
		this.z = z;
	}
	
	public MovePawnRequestDTO () {};
}