/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package el_dorado.domain;
//text
public class Field {
    private int number = 1;
    
    public int getNumber () {
    	return this.number;
    }
}
