/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api;

import jakarta.servlet.http.*;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.*;

import eldorado.domain.*;
import eldorado.api.dto.*;


@Path("/creategame")
public class CreateGame {
    @GET
	//@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response initialize(
			@Context HttpServletRequest request) {
    	
    	try {
	    	Game game = new Game(1);
	        HttpSession session = request.getSession(true);
	        session.setAttribute("game", game);
	        
    		GameStateDTO gameStateDTO = new GameStateDTO (game);
			return Response.status(200).entity(gameStateDTO).build();
    	} catch (Exception e) {
    		return Response.status(500).build();
    	}
	}
}
