/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api;

import jakarta.servlet.http.*;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.*;

import eldorado.domain.*;

@Path("/creategame")
public class CreateGame {
    @GET
	//@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response initialize(
			@Context HttpServletRequest request) {
    	
    	Game game = new Game(0);
        HttpSession session = request.getSession(true);
        session.setAttribute("game", game);
        
		return Response.status(200).entity(game.getCurrentStateDTO()).build();
	}
}
