/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api;

import jakarta.servlet.http.*;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.*;

import eldorado.domain.*;

import java.util.ArrayList;

import eldorado.api.dto.*;


@Path("/endturn")
public class EndTurn {
    @POST
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	public Response initialize(
			@Context HttpServletRequest request,
			EndTurnRequestDTO requestDTO) {
    	try {
    		HttpSession session = request.getSession(true);
    		Game game = (Game) session.getAttribute("game");
    		ArrayList<String> cardsToKeep = new ArrayList<String>();
    		for (String card : requestDTO.selectedCards) {
    			cardsToKeep.add(card);
    		}
    		game.endTurn(cardsToKeep);
    		
    		GameStateDTO gameStateDTO = new GameStateDTO (game);
			return Response.status(200).entity(gameStateDTO).build();
    	} catch (Exception e) {
    		return Response.status(500).build();
    	}
	}
}
