/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

//import static org.junit.Assert.*;
//import org.junit.Test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ConfiguredMapTest {
	
	String[][] testConfigs = {
			{"0,0,0"}
	};
	
    @Test 
    public void newFieldHasCenterPos() {
    	ConfiguredMap map = new ConfiguredMap(testConfigs[0]);
        assertNotNull(map.getField(0, 0, 0));
    }
}
