/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

//import static org.junit.Assert.*;
//import org.junit.Test;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Map;

public class DeckTest {
    
    @Test
    public void checkStartingDeckConfiguration() {
    	Deck deck = new Deck();
		assertEquals(4, deck.getHand().size());
    }
}
