/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

//import static org.junit.Assert.*;
//import org.junit.Test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class FieldTest {
	
    @Test 
    public void newFieldHasCenterPos() {
        Field field = new Field();
        assertNotNull(field);
        assertNotNull(field.pos);
        assertNotNull(field.pos.x);
        assertEquals(0, field.pos.x);
        assertEquals(0, field.pos.y);
        assertEquals(0, field.pos.z);
    }
}
