/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

//import static org.junit.Assert.*;
//import org.junit.Test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class FieldTest {
	
    @Test 
    public void testField() {
        ElDorado elDorado = new ElDorado();
        assertEquals("Hello world", elDorado.getText());
    }
}
