/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class Card {
	public final String type;
	
	public Card (String type) {
		this.type = type;
	}
}