/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

import java.util.Map;
import java.util.HashMap;

public class ConfiguredMap {
	private static String strSep = ",";
	
	public Map<String, Field> fields = new HashMap<String, Field>();
			
	public ConfiguredMap (String[] mapConfiguration) {
		// input format: {"x,y,z", "x,y,z", etc.}
		for (String fieldConfig : mapConfiguration) {
			this.tryAddFieldToConfig(fieldConfig);
		}
	}
	
	private void tryAddFieldToConfig(String fieldConfig) {
		String[] fieldValues = fieldConfig.split(strSep);
		int x = Integer.parseInt(fieldValues[0]);
		int y = Integer.parseInt(fieldValues[1]);
		int z = Integer.parseInt(fieldValues[2]);
		if (!this.hasPosField(x,y,z)) {
			Field newField = new Field();
			this.addField(x, y, z, newField);
		}
	}
	
	private boolean hasPosField (int x, int y, int z) {
		String posKey = composePosKey (x,y,z);
		return this.fields.containsKey(posKey);
	}
	
	public Field getField (int x, int y, int z) {
		return this.fields.get(composePosKey(x,y,z));
	}
	
	private void addField (int x, int y, int z, Field field) {
		this.fields.put(composePosKey(x,y,z), field);
	}
	
	private String composePosKey (Integer x, Integer y, Integer z) {
		return String.join(strSep, x.toString(), y.toString(), z.toString());
	} 
	
	public ConfiguredMap_JSONed getJSONed () {
		return new ConfiguredMap_JSONed(this.fields);
	}
	
	public class ConfiguredMap_JSONed {
		public String[] fields_asArray;
	
		public ConfiguredMap_JSONed (Map<String, Field> fields) {
			this.addFieldsAsArray(fields);
		}
			
		private void addFieldsAsArray (Map<String, Field> fields) {
			this.fields_asArray = new String[fields.size()];
			int i = 0;
			for (Map.Entry<String, Field> posKey: fields.entrySet()) {
				this.fields_asArray[i] = posKey.getKey();
				i++;
			}
		}
	}

	class Field {
		public Field () {
		}
	}
	
	public static String[][] mapConfigs = {
		{
			"0,0,0","0,1,1","0,3,3,","0,4,4",
			"1,0,1","1,1,2","1,2,3","1,3,4",
			"2,0,2","2,2,4","2,3,5",
			"3,-1,2","3,0,3","3,2,5"}
	};
}
