/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class CoordinatesDTO {
	public int x;
	public int y;
	public int z;
	
	public CoordinatesDTO (String coordinatesKeyString) {
		String[] coordinates = coordinatesKeyString.split(MapConfiguration.seperator);
		this.x = Integer.parseInt(coordinates[0]);
		this.y = Integer.parseInt(coordinates[1]);
		this.z = Integer.parseInt(coordinates[2]);
	}
}