/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

import java.util.ArrayList;
import java.util.Random;

public class Deck {
	private ArrayList<String> deck;
	private ArrayList<String> hand;
	private ArrayList<String> discarded;
	
	private static String[] defaultStarterDeck = {
			CardType.sailor,
			CardType.explorer,
			CardType.explorer,
			CardType.explorer,
			CardType.traveler,
			CardType.traveler,
			CardType.traveler,
			CardType.traveler
	};
    private static Random random = new Random();
	
	public Deck () {
		this.deck = createStarterDeck();
		this.hand = new ArrayList<String>();
		this.discarded = new ArrayList<String>();
	}
	
	public void draw (int amountToDraw) {
		int amountLeftToDraw = amountToDraw - 1;
		String randomCardFromDeck = this.deck.get(random.nextInt(this.deck.size()));
		this.deck.remove(randomCardFromDeck);
		this.hand.add(randomCardFromDeck);
		
		if (amountLeftToDraw > 0) {
			this.draw(amountLeftToDraw);
		}
	}
	
	public ArrayList<String> getDeck () {
		return this.deck;
	}
	
	public ArrayList<String> getHand () {
		return this.hand;
	}
	
	public ArrayList<String> getDiscarded () {
		return this.discarded;
	}
	
	public boolean handContainsCard (String card) {
		return (this.getHand().contains(card));
	}
	
	public void discard (String discardedCard) {
		this.getHand().remove(discardedCard);
		this.getDiscarded().add(discardedCard);
	}
		
	private static ArrayList<String> createStarterDeck () {
		ArrayList<String> starterDeck = new ArrayList<String>();
		for (int i=0; i<defaultStarterDeck.length; i++) {
			starterDeck.add(defaultStarterDeck[i]);
		}
		return starterDeck;
	}
	
	public class CardType {
		public static final String explorer = "explorer";
		public static final String sailor = "sailor";
		public static final String traveler = "traveler";
	}
}
