/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

import java.util.ArrayList;
import java.util.Random;

public class Deck {
	private ArrayList<Card> deck;
	private ArrayList<Card> hand;
	private ArrayList<Card> discarded;
	
	private static String[] defaultStarterDeck = {
			FieldType.sea,
			FieldType.jungle,
			FieldType.jungle,
			FieldType.jungle,
			FieldType.village,
			FieldType.village,
			FieldType.village,
			FieldType.village
	};
    private static Random random = new Random();
	
	public Deck () {
		this.deck = createStarterDeck();
		this.hand = new ArrayList<Card>();
		this.discarded = new ArrayList<Card>();
		this.drawCard(4);
	}
	
	public void drawCard (int amountToDraw) {
		int amountLeftToDraw = amountToDraw - 1;
		Card randomCardFromDeck = this.deck.get(random.nextInt(this.deck.size()));
		this.deck.remove(randomCardFromDeck);
		this.hand.add(randomCardFromDeck);
		
		if (amountLeftToDraw > 0) {
			this.drawCard(amountLeftToDraw);
		}
	}
	
	public ArrayList<Card> getHand () {
		return this.hand;
	}
		
	private static ArrayList<Card> createStarterDeck () {
		ArrayList<Card> starterDeck = new ArrayList<Card>();
		for (int i=0; i<defaultStarterDeck.length; i++) {
			starterDeck.add(new Card(defaultStarterDeck[i]));
		}
		return starterDeck;
	}
}
