/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;
//text
public class ElDorado {
    private String text = "Hello world";
    
    public String getText () {
    	return this.text;
    }
}
