/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class Field {
	private int pawnId = 0;
	
	public Field (int pawnId) {
		this.setPawnId(pawnId);
	}		
	
	public boolean isOccupied () {
		return (pawnId > 0);
	}
	
	public int getPawnId () {
		return pawnId;
	}
	
	public void setPawnId (int pawnId) {
		this.pawnId = pawnId;
	}
}