/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class FieldTypes {
	public static final String jungle = "jungle";
	public static final String sea = "sea";
	public static final String village = "village";
	public static final String eldorado = "eldorado";
	public static final String mountain = "mountain";
}