/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class FieldDTO {
	public CoordinatesDTO coordinatesDTO;
	public Field fieldStateDTO;
	
	public FieldDTO (String coordinatesKey, Field field) {
		this.coordinatesDTO = new CoordinatesDTO(coordinatesKey);
		this.fieldStateDTO = field;
	}
}