/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class Game {
	
	private MapConfiguration map;
			
	public Game (int mapConfigurationId) {
		this.map = new MapConfiguration(mapConfigurationId);
	}
	
	public MapConfiguration getMap () {
		return this.map;
	}
	
	public GameStateDTO getCurrentStateDTO () {
		return new GameStateDTO(this);
	}
}