/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class GameStateDTO {
	public final MapStateDTO mapStateDTO;

	public GameStateDTO (Game game) {
		this.mapStateDTO = new MapStateDTO(game.getMap());
	}
}