/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class Game {
	
	private MapConfiguration map;
	private int winningPawnId = 0;
	private Deck deck;
			
	public Game (int mapConfigurationId) {
		this.initialize(new MapConfiguration(mapConfigurationId));
	}
	
	public Game (String[][] mapConfiguration) {
		this.initialize(new MapConfiguration(mapConfiguration));
	}
	
	private void initialize (MapConfiguration mapConfiguration) {
		this.map = mapConfiguration;
		this.deck = new Deck();
		deck.refillHand();		
	}
	
	public MapConfiguration getMap () {
		return this.map;
	}
	
	public boolean canPawnMoveFromFieldToFieldUsingCard_andIsThatCardPresentInHand (int pawnId, Field pawnCurrentField, Field pawnFieldToMoveTo, String selectedCard) {
		if (pawnCurrentField != null 
				&& pawnFieldToMoveTo != null 
				&& pawnFieldToMoveTo.type != Field.Type.mountain 
				&& pawnFieldToMoveTo.isValidCardForMove(selectedCard)
				&& this.deck.handContainsCard(selectedCard)) {
			return true;
		} else {
			return false;
		}
	}
	
	public void processPossibleWin (Field newlyOccupiedField) {
		if (newlyOccupiedField.isOccupied() && newlyOccupiedField.type == "eldorado") {
			this.setWinningPawnId(newlyOccupiedField.getPawnId());
		}
	}
	
	public void setWinningPawnId (int winningPawnId) {
		this.winningPawnId = winningPawnId;
	}
	
	public int getWinningPawnId () {
		return this.winningPawnId;
	}
	
	public Deck getDeck () {
		return this.deck;
	}
	
	public void endTurn () {
		this.deck.refillHand();
	}
}