/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public class Game {
	
	private MapConfiguration map;
	private int winningPawnId = 0;
			
	public Game (int mapConfigurationId) {
		this.map = new MapConfiguration(mapConfigurationId);
	}
	
	public Game (String[][] mapConfiguration) {
	this.map = new MapConfiguration(mapConfiguration);
	}
	
	public MapConfiguration getMap () {
		return this.map;
	}
	
	public void setWinningPawnId (int winningPawnId) {
		this.winningPawnId = winningPawnId;
	}
	
	public int getWinningPawnId () {
		return this.winningPawnId;
	}
	
	public void processPossibleWin (Field newlyOccupiedField) {
		if (newlyOccupiedField.isOccupied() && newlyOccupiedField.type == "finish") {
			this.setWinningPawnId(newlyOccupiedField.getPawnId());
		}
	}
}