/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.domain;

public abstract class Maps {

	public static final String[][][] config = {
		{
			{"0,0,0", "0"},
			{"0,1,1", "1"},
			{"0,3,3", "0"},
			{"0,4,4", "0"},
			{"1,0,1", "0"},
			{"1,1,2", "0"},
			{"1,2,3", "0"},
			{"1,3,4", "0"},
			{"2,0,2", "0"},
			{"2,2,4", "0"},
			{"2,3,5", "0"},
			{"3,-1,2", "0"},
			{"3,0,3", "0"},
			{"3,2,5", "0"}
		}
	};
};