/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eldorado.api;

//import static org.junit.Assert.*;
//import org.junit.Test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import eldorado.domain.*;

public class CreateGameTest {

}
